version: '3.8'

services:
  app:
    image: ghcr.io/curol/devcontainers/js-pnpm:latest
    user: vscode
    volumes:
      - commandhistory:/workspaces/commandhistory
      - next-auth-example:/workspaces/next-auth-example
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock 
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/bash -c "sleep infinity"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # ports:
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - next-auth-example-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nextauth
      MYSQL_USER: user
      MYSQL_PASSWORD: password1234

volumes:
  next-auth-example-data: